version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=sxannyy
      - POSTGRES_PASSWORD=7721
      - POSTGRES_DB=mischiefkid
    ports:
      - "5432:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge